### ISSUE TITLE
NHM Profitability Data Error

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner#194]
![image](https://user-images.githubusercontent.com/24593637/29508069-c2d97564-865b-11e7-94dd-64e6e1af429f.png)

`[2017-08-21 10:28:49] [INFO] [NICEHASH] Starting up NiceHashMiner v1.8.1.1
[2017-08-21 10:28:49] [INFO] [NICEHASH] Selected language: English
[2017-08-21 10:28:49] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2017-08-21 10:28:49] [INFO] [SystemSpecs] FreePhysicalMemory = 2843480
[2017-08-21 10:28:49] [INFO] [SystemSpecs] FreeSpaceInPagingFiles = 15894260
[2017-08-21 10:28:49] [INFO] [SystemSpecs] FreeVirtualMemory = 18537916
[2017-08-21 10:28:49] [INFO] [SystemSpecs] LargeSystemCache = 0
[2017-08-21 10:28:49] [INFO] [SystemSpecs] MaxNumberOfProcesses = 4294967295
[2017-08-21 10:28:49] [INFO] [SystemSpecs] MaxProcessMemorySize = 8589934464
[2017-08-21 10:28:49] [INFO] [SystemSpecs] NumberOfLicensedUsers = 0
[2017-08-21 10:28:49] [INFO] [SystemSpecs] NumberOfProcesses = 73
[2017-08-21 10:28:49] [INFO] [SystemSpecs] NumberOfUsers = 2
[2017-08-21 10:28:49] [INFO] [SystemSpecs] OperatingSystemSKU = 1
[2017-08-21 10:28:49] [INFO] [SystemSpecs] SizeStoredInPagingFiles = 16777216
[2017-08-21 10:28:49] [INFO] [SystemSpecs] SuiteMask = 272
[2017-08-21 10:28:49] [INFO] [SystemSpecs] TotalSwapSpaceSize = 0
[2017-08-21 10:28:49] [INFO] [SystemSpecs] TotalVirtualMemorySize = 33499588
[2017-08-21 10:28:49] [INFO] [SystemSpecs] TotalVisibleMemorySize = 16724232
[2017-08-21 10:28:49] [INFO] [NICEHASH] Total RAM: 16332MB
[2017-08-21 10:28:49] [INFO] [NICEHASH] Page File Size: 16382MB
[2017-08-21 10:28:49] [INFO] [NICEHASH] Balance update
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ccminer
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ccminer_CryptoNight
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ethminer_OCL
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ethminer_CUDA
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_sgminer
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_cpuminer_opt
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_nheqminer_CPU
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_nheqminer_CUDA
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_eqm_CUDA
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreZcash
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreCryptoNight
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_OptiminerZcash
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_excavator
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreDual
[2017-08-21 10:28:49] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_EWBF
[2017-08-21 10:28:49] [INFO] [ComputeDeviceManager.Query] Copy from C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll to E:\Downloads\Mining\NiceHashMiner\NHML-1.8.1.1\nvml.dll done
[2017-08-21 10:28:49] [INFO] [ComputeDeviceManager.Query] 
QueryVideoControllers: 
	Win32_VideoController detected:
		Name NVIDIA GeForce GTX 460
		Description NVIDIA GeForce GTX 460
		PNPDeviceID PCI\VEN_10DE&DEV_0E22&SUBSYS_086510DE&REV_A1\4&63638AD&0&0008
		DriverVersion 21.21.13.7254
		Status OK
		InfSection Section002
		AdapterRAM 1073741824
	Win32_VideoController detected:
		Name NVIDIA GeForce GTX 780
		Description NVIDIA GeForce GTX 780
		PNPDeviceID PCI\VEN_10DE&DEV_1004&SUBSYS_27843842&REV_A1\4&41805E8&0&000A
		DriverVersion 21.21.13.7254
		Status OK
		InfSection Section032
		AdapterRAM 3221225472
	Win32_VideoController detected:
		Name NVIDIA GeForce GTX 780 Ti
		Description NVIDIA GeForce GTX 780 Ti
		PNPDeviceID PCI\VEN_10DE&DEV_100A&SUBSYS_28833842&REV_A1\4&3EA651A&0&0009
		DriverVersion 21.21.13.7254
		Status OK
		InfSection Section032
		AdapterRAM 3221225472

[2017-08-21 10:28:49] [INFO] [ComputeDeviceManager.Query] QueryCPUs START
[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] HyperThreadingEnabled = TRUE
[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] QueryCPUs END
[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] QueryCudaDevices START
[2017-08-21 10:28:51] [INFO] [NVAPI] Found handle for busid 1
[2017-08-21 10:28:51] [INFO] [NVAPI] Found handle for busid 2
[2017-08-21 10:28:51] [INFO] [NVAPI] Found handle for busid 3
[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] 
CudaDevicesDetection:
	ADDED device:
		ID: 0
		BusID: 2
		NAME: EVGA GeForce GTX 780 Ti
		VENDOR: EVGA
		UUID: GPU-3c24d0ab-be17-987b-e735-3c79109bd094
		SM: 3.5
		MEMORY: 3221225472
		ETHEREUM: YES
	ADDED device:
		ID: 1
		BusID: 3
		NAME: EVGA GeForce GTX 780
		VENDOR: EVGA
		UUID: GPU-bc77740e-6e9d-b167-4b33-2f2ed80a0270
		SM: 3.5
		MEMORY: 3221225472
		ETHEREUM: YES
	ADDED device:
		ID: 2
		BusID: 1
		NAME: NVIDIA GeForce GTX 460
		VENDOR: NVIDIA
		UUID: GPU-3f23f02b-41a8-17f2-3b82-44feaecda057
		SM: 2.1
		MEMORY: 1073741824
		ETHEREUM: NO

[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] QueryCudaDevices END
[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] Skipping AMD device detection, settings set to disabled
[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] Cuda NVIDIA/CUDA device count GOOD
[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] AMD GPU device count GOOD
[2017-08-21 10:28:51] [INFO] [ComputeDeviceManager.Query] virtual memory size GOOD
[2017-08-21 10:28:52] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-08-21 10:28:52] [INFO] [SOCKET] Attempting reconnect in 0 seconds
[2017-08-21 10:28:52] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-08-21 10:28:54] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-08-21 10:28:55] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-08-21 10:28:57] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-08-21 10:28:58] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-08-21 10:29:00] [INFO] [NICEHASH] Bitcoin rate get
[2017-08-21 10:29:00] [INFO] [NICEHASH] Current Bitcoin rate: 4020.71
[2017-08-21 10:29:00] [INFO] [NICEHASH] Setting environment variables
[2017-08-21 10:29:00] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
[2017-08-21 10:29:00] [INFO] [NICEHASH] Current DontShowUI value: 1
[2017-08-21 10:29:00] [INFO] [NICEHASH] nvidiasetp0state all OK
`

**Comment by Spoob** [comment]
Similar behavior. A couple of days as it began. I have a restart from time to time due to problems with the power supply. At startup, the client can not receive data from the server. Experienced, I found that this is how 1.8.1.0 and 1.8.1.1 behave. If you use an older version, for example 1.8.0.2 - it connects stably without problems. She's older, but better than not.

**Comment by Spoob** [comment]
Update. 1.8.0.2 does not solve the problem. When restarting, it can also stand and wait for the solution to report that there is no Internet connection. But the connection is there. I connect remotely

**Comment by KristoferV** [comment]
I have it on my personal PC, today it just doesn' t want to connect, have done multiple restarts. +1 to this issue.

**Comment by nicehashdev** [comment]
Your problem should be fixed now.

**Comment by Pruxa-sun** [comment]
Have same problem today. After my attempts to get Legacy 1.8.1.1 running, NHM 1.7.5.13 start getting same profitability error, after 10 minutes profitability error with 1.7.5.13 dissapeared. Still having this error with Legacy 1.8.1.1

**Comment by Spoob** [comment]
The problem with 1.8.1.1 is still present. Hangs on receiving SMA data. You have to remove the process from the taskbar

**Comment by Pruxa-sun** [comment]
Yes 1 of my PC hangs on, 1 gets error message. On 3 Pc's i was able to launch legacy 1.8.1.1. What is really starange cuz all of them connects to the same router. All have same Windows version.

**Comment by KristoferV** [comment]
I am on 1.8.1.1 and it works now

**Comment by DillonN** [comment]
If you are getting hangs on getting NH SMA could you please post logs and be sure it is actually hanging (instead of the error prompt popping up behind the main window)

**Comment by Pruxa-sun** [comment]
now everything ok

**Comment by Pruxa-sun** [comment]
Today got again that error. [2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] QueryOpenCLDevices END
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] QueryAMD START
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA GeForce GTX 1070 (22.21.13.8494)
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA GeForce GTX 1070 (22.21.13.8494)
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA GeForce GTX 1070 (22.21.13.8494)
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA GeForce GTX 1070 (22.21.13.8494)
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA GeForce GTX 1070 (22.21.13.8494)
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA GeForce GTX 1070 (22.21.13.8494)
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] QueryAMD END
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] Cuda NVIDIA/CUDA device count GOOD
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] AMD GPU device count GOOD
[2017-09-02 10:57:33] [INFO] [ComputeDeviceManager.Query] virtual memory size GOOD
[2017-09-02 10:57:34] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-09-02 10:57:34] [INFO] [SOCKET] Attempting reconnect in 0 seconds
[2017-09-02 10:57:34] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-09-02 10:57:36] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-09-02 10:57:37] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-09-02 10:57:38] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-09-02 10:57:39] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
[2017-09-02 10:57:43] [INFO] [NICEHASH] Bitcoin rate get
[2017-09-02 10:57:43] [INFO] [NICEHASH] Удаленный сервер возвратил ошибку: (404) Не найден.
[2017-09-02 10:57:43] [INFO] [ExchangeRateAPI] UpdateAPI got NULL
[2017-09-02 10:57:43] [INFO] [NICEHASH] Current Bitcoin rate: 0.00
[2017-09-02 10:57:43] [INFO] [NICEHASH] Setting environment variables
[2017-09-02 10:57:43] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
[2017-09-02 10:57:43] [INFO] [NICEHASH] Current DontShowUI value: 1
[2017-09-02 10:57:43] [INFO] [CurrencyConverter] Unable to retrieve update, Falling back to USD

**Comment by Pruxa-sun** [comment]
All good now. But i wonder why only 1 of my PC got this mistake.

**Comment by Pruxa-sun** [comment]
Now ur wonderfull Legacy got another bug. Start getting dialog window on all of my PCs with profitability error even if gets all data correctly what means that mining won't start if the systems reboots cuz u need to click on OK button in that window and then u need to press start mining. Pls fix that bug.
