### ISSUE TITLE
"Share Above Target" Error

### ISSUE THREAD

**Issue by faith1001** [nicehash/NiceHashMiner#2133]
Hi there,

I am using GTX1080 and using NBMiner to mine DaggerHashimoto. It was fine until recently I am getting "Share above target" errors causing share rejects. Strangely, this happens on only one of my two GPUs. Both my GPUs are identical. Attached below are a screenshot and the log file. Hopefully you can help advise me. Thank you.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/5069843/log.txt)

![error](https://user-images.githubusercontent.com/69380820/90152210-286b5600-ddba-11ea-9ca6-c7b18596490c.jpg)

**Comment by luc1an24** [comment]
Hi @faith1001 
Thank you for reaching out.
This is a connection problem with the pool and it should be fixed by now.
Could you confirm it?
Thank you!

**Comment by faith1001** [comment]
I am sorry but the error still persists. Same issue when NBMiner is used to mine other coins. No problem with other miners like GMiner.

**Comment by luc1an24** [comment]
Thank you for feedback
Did you check other miners on Dagger as well?
We started getting this issue again on all miners.
NBMiner on other hand works fine on other algorithms.
Could you post some screenshots of NBMiner failing on other algos as KawPow?
Have a nice day!

**Comment by faith1001** [comment]
Hi there,
Unfortunately, the problem with NBMiner mining Dagger still persisted so I have stopped using it. I tried using Phoenix to mine Dagger and still encounter error. That forces it to run many instances of Phoenix miner. Screenshot below:

![1](https://user-images.githubusercontent.com/69380820/93476794-c22fa100-f92c-11ea-9020-912d9e0e5786.png)

**Comment by Dohtar1337** [comment]
Share above target means that you used to high overclock settings. Lower it
