### ISSUE TITLE
'Time Unit' isn't translateable in 1.8.1.4-Pre3

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#427]
**Preconditions:** NHML 1.8.1.4-Pre3, any language including English

1) Start NHML
2) Open **Settings** window

**Result:** there is a field named 'TimeUnit' (without a space)
**Expected result:** a corresponding translation used in the lang-file, for English it is 'Time Unit' (with space) - https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/langs/en.lang#L22
![image](https://user-images.githubusercontent.com/4707112/31574775-4a7053e8-b0e7-11e7-899a-e839cffd960b.png)

**Comment by mcsjohn** [comment]
Already fixed in my pull request https://github.com/nicehash/NiceHashMinerLegacy/pull/403

**Comment by adem4ik** [comment]
This is still an issue in 1.9.0.20. Possible fix could be taken from https://github.com/nicehash/NiceHashMinerLegacy/pull/403/commits/b983d208c1c350032450d7c05e296491ed1fd729

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

We will be working on a complete GUI re-design.

Issue is solved with latest release
